export const ROLES = {

    ADMIN: 'admin',
    EMPLOYEE: 'employee',
} as const

export const ROUTES = {
    HOME: '/',
    LOGIN: '/login',
    FORBIDDEN: '/forbidden',
    DASHBOARD: '/dashboard',
    PURCHASE_INVOICES: '/invoices/purchase',
    CREATE_PURCHASE_INVOICES: '/invoices/purchase/create',
    PURCHASE_INVOICE_DETAILS: '/invoices/purchase/details',
    MANUFACTURING_INVOICE: '/invoices/manufacturing',
    CREATE_MANUFACTURING_INVOICE: '/invoices/manufacturing/create',
    MANUFACTURING_INVOICE_DETAILS: '/invoices/manufacturing/details',
    INVENTORY_LEVEL_REPORT: '/reports/inventory-level',
    CATEGORIES: '/categories',
    INVENTORIES: '/inventories',
    SUPPLIERS: '/suppliers',
    COUNTRIES: '/countries',
    CITIES: '/cities',
    ITEM_GROUPS: '/item-groups',
    TRANSFER_INVOICE: '/invoices/transfer',
    CREATE_TRANSFER_INVOICE: '/invoices/transfer/create',
    TRANSFER_INVOICE_DETAILS: '/invoices/transfer/details',
    CREATE_ITEM: '/items/create',
    EDIT_ITEM: '/items/edit',
    ITEMS: '/items/raw',
    FULL_PRODUCED_ITEMS: '/items/full-produced',
    HALF_PRODUCED_ITEMS: '/items/half-produced',
    REVERSE_PRODUCED_ITEMS: '/items/reverse-produced',
    SERVICEABLE_ITEMS: '/items/serviceable',
    ITEMS_TRANSACTIONS: '/items/transactions',
    INVENTORY_TRANSACTIONS: '/inventory-transaction',
    MOST_BUY_ITEMS: '/most-buy-items',
    UNITS: '/units',
    GOODS_INVOICE: '/invoices/goods',
    CREATE_GOODS_INVOICE: '/invoices/goods/create',
    GOODS_INVOICE_DETAILS: '/invoices/goods/details',
    ITEMS_TREE: '/items-tree',
    SELL_INVOICES: '/invoices/sell',
    CREATE_SELL_INVOICES: '/invoices/sell/create',
    SELL_INVOICE_DETAILS: '/invoices/sell/details',
    WASTE_INVOICE: '/invoices/waste',
    CREATE_WASTE_INVOICE: '/invoices/waste/create',
    WASTE_INVOICE_DETAILS: '/invoices/waste/details',
    CONSUMPTION_INVOICE: '/invoices/consumption',
    CREATE_CONSUMPTION_INVOICE: '/invoices/consumption/create',
    CONSUMPTION_INVOICE_DETAILS: '/invoices/consumption/details',
    COST_ANALYSIS: '/cost-analysis/create',
    COST_ANALYSIS_TABLE: '/cost-analysis',
    COST_ANALYSIS_DETAILS: '/cost-analysis/details',
    RETURN_INVOICES: '/invoices/return',
    CREATE_RETURN_INVOICES: '/invoices/return/create',
    RETURN_INVOICE_DETAILS: '/invoices/return/details',
    INVENTORY_COUNTS: '/inventory-counts',
    CREATE_INVENTORY_COUNT: '/inventory-counts/create',
    INVENTORY_COUNT_DETAILS: '/inventory-counts',
    CONTINUE_INVENTORY_COUNT: '/inventory-counts/continue',
    INVENTORY_ADJUSTMENT: '/inventory-counts/adjust',
    PRODUCED_ITEMS_MARGIN: '/produced-items-margin',
    SETTINGS: '/settings',
    CURRENCIES: '/currencies',
    MINIMUM_QUANTITY_REPORT: '/reports/minimum-quantity',
    EXPIRY_ITEMS_REPORT: '/reports/expiry-items',
    SUPPLIER_TRANSACTIONS: '/reports/supplier-transactions',
    ITEM_MOVEMENT_REPORT: '/reports/item-movement',
};

export const SUPPLIER_TYPE = {
    SUPPLIER: 'supplier',
    CUSTOMER: 'customer',
    BOTH: 'both',
} as const

export const PAYMENT_METHOD = {
    CASH: 'Cash',
    CREDIT: 'Credit',
    BANK_TRANSFER: 'bank_transfer',
} as const